a = (input('Digite algo:'))
classe = type(a)
espaco = a.isspace()
num = a.isnumeric()
alfa = a.isalpha()
alfanum = a.isalnum()
maisculo = a.isupper()
minusculo = a.islower()
capitalizada = a.istitle()
print('O tipo primitivo desse valor é {}.'.format(classe))
print('Só tem espaços? {}'.format(espaco))
print('É um número? {}'.format(num))
print('É alfabetico ? {}'.format(alfa))
print('É alfanumeric? {}'.format(alfanum))
print('É maiusculo? {}'.format(maisculo))
print('É minusculo? {}'.format(minusculo))
print('Está capitalizada? {}'.format(capitalizada))
